In [45]:
import numpy as np

In [46]:
#Создание массива из обычного списка
list_array = np.array([1, 2, 3, 4, 5])
print("Массив из списка:", list_array)

Массив из списка: [1 2 3 4 5]


In [47]:
#Создание массива из двумерного списка
list_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Двумерный массив из списка:", list_2d_array)

Двумерный массив из списка: [[1 2 3]
 [4 5 6]]


In [48]:
#Создание массива с помощью zeros
zeros_array = np.zeros(5)
print("Массив из нулей:", zeros_array)

Массив из нулей: [0. 0. 0. 0. 0.]


In [49]:
#Создание двумерного массива из нулей
zeros_2d_array = np.zeros((3, 4))
print("Двумерный массив из нулей:", zeros_2d_array)

Двумерный массив из нулей: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [50]:
#Создание массива с помощью ones
ones_array = np.ones(5)
print("Массив из единиц:", ones_array)

Массив из единиц: [1. 1. 1. 1. 1.]


In [51]:
#Создание двумерного массива из единиц
ones_2d_array = np.ones((2, 3))
print("Двумерный массив из единиц:", ones_2d_array)

Двумерный массив из единиц: [[1. 1. 1.]
 [1. 1. 1.]]


In [52]:
#Создание массива с помощью arange
arange_array = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
print("Массив с помощью arange:", arange_array)

Массив с помощью arange: [0 2 4 6 8]


In [53]:
#Создание массива с помощью linspace
linspace_array = np.linspace(0, 1, 5)  # 5 равномерно распределенных значений от 0 до 1
print("Массив с помощью linspace:", linspace_array)

Массив с помощью linspace: [0.   0.25 0.5  0.75 1.  ]


In [54]:
#Демонстрация атрибутов
sample_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Массив для демонстрации атрибутов:", sample_array)
print("Форма (shape):", sample_array.shape)  # форма массива
print("Тип данных (dtype):", sample_array.dtype)  # тип данных элементов массива

Массив для демонстрации атрибутов: [[1 2 3]
 [4 5 6]]
Форма (shape): (2, 3)
Тип данных (dtype): int32


In [ ]:
#Примеры индексирования и срезов

#Получение отдельного элемента
element = sample_array[1, 2]  # элемент в 1-ой строке, 2 столбец
print("\nОтдельный элемент [1, 2]:", element)


Отдельный элемент [1, 2]: 6


In [56]:
#Извлечение подмассива с помощью среза
subarray = sample_array[0:2, 1:3]  # строки с 0 по 1, столбцы с 1 по 2
print("Подмассив с помощью среза [0:2, 1:3]:", subarray)


Подмассив с помощью среза [0:2, 1:3]: [[2 3]
 [5 6]]


In [57]:
#Срез одной строки
row_slice = sample_array[0, :]  # первая строка
print("Первая строка:", row_slice)


Первая строка: [1 2 3]


In [58]:
#Срез одного столбца
col_slice = sample_array[:, 1]  # второй столбец
print("Второй столбец:", col_slice)

Второй столбец: [2 5]


In [59]:
#Примеры векторных операций и базовых статистик

#Поэлементное сложение массивов
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])
sum_array = array1 + array2
print("Массив 1:", array1)
print("Массив 2:", array2)
print("Сложение:", sum_array)

Массив 1: [1 2 3 4]
Массив 2: [5 6 7 8]
Сложение: [ 6  8 10 12]


In [60]:
#Поэлементное умножение массивов
mult_array = array1 * array2
print("Умножение:", mult_array)

Умножение: [ 5 12 21 32]


In [61]:
#Умножение на скаляр
scalar_mult = array1 * 3
print("Умножение на скаляр (3):", scalar_mult)

Умножение на скаляр (3): [ 3  6  9 12]


In [62]:
#Вычисление средней величины
mean_value = np.mean(array1)
print("Среднее значение массива 1:", mean_value)

Среднее значение массива 1: 2.5


In [63]:
#Вычисление максимального значения
max_value = np.max(array1)
print("Максимальное значение массива 1:", max_value)

Максимальное значение массива 1: 4


In [64]:
#Вычисление минимального значения
min_value = np.min(array1)
print("Минимальное значение массива 1:", min_value)

Минимальное значение массива 1: 1


In [65]:
#Вычисление суммы всех элементов
sum_value = np.sum(array1)
print("Сумма всех элементов массива 1:", sum_value)

Сумма всех элементов массива 1: 10


In [66]:
#Статистика для двумерного массива
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Матрица 3x3:", matrix)
print("Среднее значение по всей матрице:", np.mean(matrix))
print("Средние значения по строкам:", np.mean(matrix, axis=1))
print("Средние значения по столбцам:", np.mean(matrix, axis=0))
print("Максимальное значение в матрице:", np.max(matrix))

Матрица 3x3: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Среднее значение по всей матрице: 5.0
Средние значения по строкам: [2. 5. 8.]
Средние значения по столбцам: [4. 5. 6.]
Максимальное значение в матрице: 9
